### ISSUE TITLE
[BUG] in HA, the aircon autostarts in heat mode

### ISSUE THREAD

**Issue by Swalabrr** [revk/ESP32-Faikin#349]
**Faikin hardware**
this is happening with Faikin purchased

**Daikin hardware**
i'm connecting with S21

**Describe the bug**
whenever the aircon is requested to start from within HA, regardless of how the request has been made -- manual or through scripting -- the aircon will start in Heat mode

```
  - service: climate.set_hvac_mode
    data:
      hvac_mode: cool
    target:
      device_id:
        - 1e7002676ea1b51a562a14e2de5b01c3
  - service: climate.set_temperature
    data:
      temperature: 23.5
      hvac_mode: cool
    target:
      device_id:
        - 1e7002676ea1b51a562a14e2de5b01c3
  - service: climate.turn_on
    data: {}
    target:
      device_id: 1e7002676ea1b51a562a14e2de5b01c3
```

**To Reproduce**
start AC, switch to dry or cool,
stop AC, 
start AC. It will start in heating mode

**Expected behavior**
start in the last selected mode

**Aditional info**

also, just setting the HVAC mode or the temp through scripting will start the AC unit (but it will start with the selected HVAC / temp)

**Comment by revk** [comment]
Is this through HA?

Is this legacy URLs or MQTT?

Does it do the same using the web interface (unlikely)?

Can you dump the mqtt messages being sent or http requests sent?

**Comment by Swalabrr** [comment]
yes, it is through HA using MQTT. It does NOT behave the same using the webinterface.

I'd like to dump the mqtt, but I have no idea how to do that. Do you mean "debug" on webinterface?

**Comment by revk** [comment]
There are tools to show what is happening on MQTT. I think even HA can do it. But not sure which to recommend.

**Comment by Nick-Sills** [comment]
@Swalabrr Try MQTT Explorer and monitor the messages. 

https://mqtt-explorer.com/

**Comment by Nick-Sills** [comment]
I notice exactly the same issue, and checking the MQTT messages and it looks like HA is sending a 'Heat'  command MQTT message when the 'On' button is clicked.  Is there even an exposed MQTT 'On' command in Faikin? 

It's also behaving exactly the same with the 'Legacy' HTTP integration, and always starting in Heat mode. However, the official Daikin WiFi board **does start with the correct HVAC mode**, i.e, it starts with the last HVAC mode before it was turned off. I can debug this and get back with my findings. 

@revk Do you want me to create an additional issue for the the HTTP integration, or handle it here?

**Comment by revk** [comment]
We have had issues with reporting hvac mode, as we don't know from S21. We do have an "on" command but HA sees off as just one of the modes it can set I believe. I assume it uses hvac mode somehow.

**Comment by Nick-Sills** [comment]
@revk I'm not sure if I was mistaken, or if the last Beta update fixed some things, but now with the **'Legacy' HTTP integration**, turning the AC Off then On retains the last HVAC mode. So, if I set to `Cool`, turn Of then On, the AC unit returns to `Cool`. 👍 

However, the Fan mode and Preset values aren't maintained, they revert to 'Auto' and 'None'. 

Comparing the HTTP response with the Daikin WiFi board I can see the issue.  

**Daikin & Faikin**
1. Turn  On - Cool, Silence, Eco
2. /aircon/get_control_info
3. Turn Of
4. /aircon/get_control_info

For **Daikin** there are no differences in any parameters returned by the first and second  `get_control_info` apart from `pow`, which is to be expected.

For **Faikin**, as well as `pow`, the following parameters are reset in the **second**  `get_control_info`, when the AC is off  ->  `f_rate`, `b_f_rate`, `dfr3` and `adv`.

So, it looks like the `dfr` array, `f_rate`, `b_f_rate`, and `adv` need to be persisted after turning off the AC with a `pow=0`, so they are returned by the next, and subsequent,  `get_control_info` calls.

Does that make sense?

As far as the MQTT climate entity not persisting sate between `Off` and `On`, I'll play with publishing some MQTT topics to see if  anything jumps out.

**Comment by Nick-Sills** [comment]
I think with MQTT we have similarly persist, and return the values in the `state` topic?

**Comment by revk** [comment]
The latest release (and beta) have a number of improvements for legacy URL handling, yes.

This includes some level of `dfr` handling. This is not persistent over restart of the Faikin, it simply persists the per mode fan value returned with `get_control_info`.

But the `f_rate` and `b_f_rate` (what does the `b_...` mean?) should persist anyway, as before.

Do you have a clear sequence of command (URLs) I could try and test here?

**Comment by Nick-Sills** [comment]
For my bedroom AC, the fact that 'Silence' fan mode is lost on power on is the most concerning issue here. 



If you need anything else then let me know.

**Fan Rate - Silence**
/set_control_info?pow=0&mode=7&stemp=20.0&shum=0&f_rate=B&f_dir=0


**Preset - Eco**
/set_special_mode?spmode_kind=2&set_spmode=1

Swing Mode Vertical and **Set Mode Cool** 
/set_control_info?pow=1&mode=3&stemp=20.0&shum=0&f_rate=B&f_dir=1

**After Power On with Set Mode Cool**
/get_control_info 
ret=OK,pow=1,mode=3,`adv=12`,stemp=20.0,shum=0,dt1=20.0,dt2=20.0,dt3=20.0,dt4=20.0,dt5=20.0,dt6=20.0,dt7=20.0,dh1=0,dh2=0,dh3=0,dh4=0,dh5=0,dh6=0,dh7=0,dhh=0,b_mode=3,b_stemp=20.0,b_shum=0,alert=255,`f_rate=B`,f_dir=1,`b_f_rate=B`,b_f_dir=1,dfr1=A,dfr2=A,`dfr3=B`,dfr4=A,dfr5=A,dfr6=A,dfr7=B,dfrh=0,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0,dmnd_run=0,en_demand=0"

**Power Off**
/set_control_info?pow=0&mode=3&stemp=20.0&shum=0&f_rate=B&f_dir=1


**After Power Off**
/get_control_info 
ret=OK,pow=0,mode=3,`adv=0`,stemp=20.0,shum=0,dt1=20.0,dt2=20.0,dt3=20.0,dt4=20.0,dt5=20.0,dt6=20.0,dt7=20.0,dh1=0,dh2=0,dh3=0,dh4=0,dh5=0,dh6=0,dh7=0,dhh=0,b_mode=3,b_stemp=20.0,b_shum=0,alert=255,`f_rate=A`,f_dir=1,`b_f_rate=A`,b_f_dir=1,dfr1=A,dfr2=A,'dfr3=A`,dfr4=A,dfr5=A,dfr6=A,dfr7=B,dfrh=0,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0,dmnd_run=0,en_demand=0"






**Power On**
/set_control_info?pow=1&mode=3&stemp=20.0&shum=0&f_rate=A&f_dir=1

| Parameter | After Set Mode Cool On | After Power Off |
|-----------|------------|-----------|
| pow       | 1          | 0         |
| adv       | 12         | 0         |
| f_rate    | B          | A         |
| b_f_rate  | B          | A         |


<hr>
<img width="356" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/162114112/7f47dbc4-bf7a-49cd-a0aa-918b80dde168">

After Power Off -> Power On

<img width="347" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/162114112/5e3e7404-c027-4b7b-86aa-35a646976516">

**Comment by revk** [comment]
Silence is a separate issue, S21 does not report silent/quiet/night mode.

We have a setting to always assume you want/have silent rather than auto.

**Comment by Nick-Sills** [comment]
I'm not sure I understand.  'f_rate` = B  is silence.  I'm not in Spain at the moment so I'm doing this remotely and can't hear the fan. I could have sworn it was working. If so, why are we resetting 'f_rate` and 'b_f_rate` to A?

**Comment by revk** [comment]
This is explained in various places in the documentation.

The underlying messages to the Daikin over S21 do not have a distinction.

We send the Daikin B and it comes back and says yes mode is A. Yes it sets silent but reports back that it is auto. Several attempts to "guess" which it is are not very good.

If anyone ever finds a flag or message to actually find that it is silent, that would be great. But nobody has yet.

There is a setting in the Faikin to always work as silent mode instead of auto mode, which may help.

**Comment by Nick-Sills** [comment]
OK, thanks for that. Can you help me understand a bit more?

If I set 'Silence' and 'Eco' then change the Fan mode from 'Auto' to 'Cool' then both 'Silence' and 'Auto' persist, so it's good. Is it just that a Power Off command changes the Fan mode to Auto on S21 (whereas in reality it's still silent).

The power off command actually contains the correct fan mode, so I wouldn't call this a guess.

**Comment by Nick-Sills** [comment]
Also it's `dfrx` array that's caching the Fan mode for each operational mode, and that's getting reset on power off.

**Comment by Nick-Sills** [comment]
Aren't we caching the `dfrx` array now because of this fix?

https://github.com/revk/ESP32-Faikin/issues/348

**Comment by Nick-Sills** [comment]
After a power off, could we lookup the `f_rate` and `b_f_rate` in the `dfrx` array  depending on the operational mode.?

**Comment by revk** [comment]
Off should not be losing fan rate setting (other than auto/silent), that puzzles me.

**Comment by revk** [comment]
Unless your Daikin is sending something different when off, we could get S21 debug and find out.

**Comment by Nick-Sills** [comment]
> Off should not be losing fan rate setting (other than auto/silent), that puzzles me.

Yes, It is losing silent, and It's also losing the Preset Mode  `adv` parameter, 

**My question is:**
We fixed a problem with Fan Modes and Preset modes by populating **and caching** the `dfr1` to `dfr7` array, and the `adv` parameter in this issue: https://github.com/revk/ESP32-Faikin/issues/348. And that includes 'Silent' and 'Auto'

I understand that we can't get the Fan Mode from S21, but in other cases we're maintaining a cache for persistence. **Isn't it possible to do the same when the Power Off - `/set_control_info?pow=0&mode=3&stemp=20.0&shum=0&f_rate=B&f_dir=1` is received?** Also the correct  `f_rate` value is sent with the `pow=0`. 

I understand it's not perfect, because the state of the fan rate could be changed by a remote or the Onecta app so the cache could be stale, but persisting the last fan rate that was set (Silence, Auto or otherwise) in the http (or MQTT) is 1000 x better than it currently is, and is actually a very good outcome.  

( I tried the Onecta app, and confirmed that 'Indoor Quiet/Silent' doesn't update the HA Climate entity, but my question still stands ) 

Can you fire the same URLs at your end, to see what I mean? 

Fan Rate - Silence
/set_control_info?pow=0&mode=7&stemp=20.0&shum=0&f_rate=B&f_dir=0

Preset - Eco
/set_special_mode?spmode_kind=2&set_spmode=1

Swing Mode Vertical and Set Mode Cool
/set_control_info?pow=1&mode=3&stemp=20.0&shum=0&f_rate=B&f_dir=1

After Power On with Set Mode Cool
/get_control_info
ret=OK,pow=1,mode=3,adv=12,stemp=20.0,shum=0,dt1=20.0,dt2=20.0,dt3=20.0,dt4=20.0,dt5=20.0,dt6=20.0,dt7=20.0,dh1=0,dh2=0,dh3=0,dh4=0,dh5=0,dh6=0,dh7=0,dhh=0,b_mode=3,b_stemp=20.0,b_shum=0,alert=255,f_rate=B,f_dir=1,b_f_rate=B,b_f_dir=1,dfr1=A,dfr2=A,dfr3=B,dfr4=A,dfr5=A,dfr6=A,dfr7=B,dfrh=0,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0,dmnd_run=0,en_demand=0"

Power Off
/set_control_info?pow=0&mode=3&stemp=20.0&shum=0&f_rate=B&f_dir=1

After Power Off
/get_control_info
ret=OK,pow=0,mode=3,adv=0,stemp=20.0,shum=0,dt1=20.0,dt2=20.0,dt3=20.0,dt4=20.0,dt5=20.0,dt6=20.0,dt7=20.0,dh1=0,dh2=0,dh3=0,dh4=0,dh5=0,dh6=0,dh7=0,dhh=0,b_mode=3,b_stemp=20.0,b_shum=0,alert=255,f_rate=A,f_dir=1,b_f_rate=A,b_f_dir=1,dfr1=A,dfr2=A,'dfr3=A`,dfr4=A,dfr5=A,dfr6=A,dfr7=B,dfrh=0,dfd1=0,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=0,dfdh=0,dmnd_run=0,en_demand=0"

**Comment by revk** [comment]
OK adv is just deduced from the other states, it is not a separate thing we get or store. So losing "silent" loses the adv as a result. So the whole issue is the lack of silent state in S21.

Now "caching" that you set silent may be a thing it could do, but it won't track if you use a remote to change from silent to auto, for example. (Note, if the real Daikin module can tell that it would be interesting as it would mean there is an unknown S21 message, which would be great to find).

At present we don't "cache" that we set silent. Maybe that could be a feature on a setting.

I have done a setting to always do silent instead of auto as plenty of people seem happy with a fan mode set low/high etc but don't need "auto" that is not "silent".

**Comment by Nick-Sills** [comment]
> Now "caching" that you set silent may be a thing it could do, but it won't track if you use a remote to change from silent to auto, for example. (Note, if the real Daikin module can tell that it would be interesting as it would mean there is an unknown S21 message, which would be great to find).

Yes, the real Daikin module can tell, but persisting the last fan rate that was set (Silence, Auto or otherwise) in the http (or MQTT) comms is 1000 x better than it currently is, and is actually a very good outcome.

> At present we don't "cache" that we set silent. Maybe that could be a feature on a setting.

That's `B` in the appropriate `dfr1` to `dfr7` array. I perhaps don't understand what is and isn't cached, or what Faikin caching is.

**Comment by Nick-Sills** [comment]
It seems that we only lose the persistence of 'Silence' and the Preset mode when  a `pow=0` is received.  Is there any chance you could explain why this command is different, and why it can't be treated like any other operational mode change?

> At present we don't "cache" that we set silent. 
`/get_control_info` after `/set_control_info?pow=1` returns `adv=12`, `f_rate=B`,`b_f_rate=B`, and `dfr3=B`. 

So, isn't that caching silence?  If not, how are we returning Silence when that can't be deduced from S21?

Apologies, for the number of questions. One of us isn't getting it, and it's probably me.

**Comment by revk** [comment]
There are a number of underlying S21 messages.

When we send a fan of B we also send temperature and power state in the same message.

We get a response confirming what we set (except it is A not B). We assume that it is B at that stage as that is what we set. We also look at things like the actual fan speed to guess that may be it has been changed to A, but when initially set to B we can assume it is B.

If you change *anything* else in that same message, we have to send all those settings again and get a response. So a change of temp will do that same.

This time the power is off, the fan is off, and we were not actually trying to "change" the fan. So when it reports A this time we assume something has changed it to A. As I say, it is guess work as that message does not differentiate A and B, always reports A.

Now, separately, and in latest code only done a few days ago, it became apparent what the dfr values were, a record of what fan rate was last used in each mode. This is not (as far as I know) anything in S21 messages. So simply remembered by the Daikin WiFi. The Faikin legacy URL code was changed to simply remember what was last reported in each mode. Ie "caching" it and reporting as dfr.

If we could find an S21 message for silent that would solve it all.

We do have a setting to always operate silent not auto, to always send B not A, and always assume A being reported means B. That works for some people.

It may be that I can make a setting to always ignore a report of A if we last set B. Basically assuming nothing else is controlling the aircon. That may do what you want close enough.

**Comment by revk** [comment]
I have issued a new beta you can try, with a new settings `noguessnight`

Try that!

**Comment by Nick-Sills** [comment]
Thanks!

Updated to: Faikin-S3-MINI-N4-R2: f760d47 2024-06-09T11:00:53
Set `noguessnight` on.

No difference I'm afraid. The same `/get_control_info` values are being returned as before, and the Fan and Preset modes are changed when turning on as before. 

I'm not sure what this change is meant to do though?

**Comment by revk** [comment]
Ok I may have got the setting wrong, try new beta in a couple of minutes. It should preserve the B you set, i.e. assuming nothing else could have set auto mode instead.

**Comment by Nick-Sills** [comment]
If I turn `noguessnight ` off it's retaining Silence. Is that the correct way round?

**Comment by revk** [comment]
No, as above 👎 
*Ok I may have got the setting wrong, try new beta in a couple of minutes. It should preserve the B you set, i.e. assuming nothing else could have set auto mode instead.*

**Comment by Nick-Sills** [comment]
Faikin-S3-MINI-N4-R2: 1524594 2024-06-09T11:18:29

Yep! That' seems to be  preserving Silence correctly. 👍  I'll run through a few more combinations, but it seems great. 

Can we do the same for `adv` ?

**Comment by revk** [comment]
As I say, `adv` is simply deduced, from `powerful`, `econo` and `streamer`, and they are read from the Daikin using separate S21. So we are back to *I would need to see the S21 messages to see why they have changed*, but my guess is that the Daikin is saying they are off.

**Comment by Nick-Sills** [comment]
Makes sense, and I've just check with the Daikin WiFi board and that's losing the preset as well, so I guess we can assume that it can't be done. 

I'll continue checking combinations, but we're looking good. 

Perhaps `noguessnight`  should be default 'On'? I guess that defaulting to 'on' might annoy existing users that expect it to behave as it did before, but TBH, I can't think why anyone would expect that, and new users won't be firing issues because they don't realize what `noguessnight` means if it was defaulted to 'On'.

**Comment by Nick-Sills** [comment]
Just one more thing...

This issue was raised for MQTT by the OP. I jumped on the thread and add HTTP to the mix, but MQTT still has the same problem. Can the MQTT state topic mirror the HTTP response changes? I think that might work.

**Comment by revk** [comment]
The change is at the S21 tracking level, so it will do the same on MQTT - try it.

**Comment by Nick-Sills** [comment]
MQTT is always going to 'Heat' when tuned on.

See last post here in case it adds anything:

https://github.com/home-assistant/core/issues/94114

**Comment by revk** [comment]
OK what message is HA sending on MQTT to turn it on exactly?

**Comment by Nick-Sills** [comment]
Hmm.. It's very difficult to interpret the MQTT stream as I've got so many MQTT messages flying around.  I had a quick pass it looked like this:

Turn on:
Faikin/Villacana AC Back Bedroom/command/mode  - heat

I assumed it was because the current 'status' topic had the an incorrect `mode` node, but I've just re-checked and it's correct, so I've no idea where 'heat' is coming from. 

BTW There are two state topics:

Faikin/Villacana AC Back Bedroom/state/status
Faikin/Villacana AC Back Bedroom/state/ha

This may be correct, but I thought it was odd. Not relevant to the 'heat' issue though. 

I'll keep poking to see if anything else jumps out....

**Comment by revk** [comment]
There are several messages sent from the Faikin, the HA status is the one ending `/ha`

**Comment by Nick-Sills** [comment]
Still digging but, when the AC is switched off from 'Cool', the `state/ha`  topic is this:

```json
{
  "online": true,
  "target": 20,
  "temp": 24,
  "outside": 27.5,
  "liquid": 15.5,
  "comp": 0,
  "demand": 100,
  "Wh": 853000,
  "fanfreq": 0,
  `"mode": "off"`,
  "fan": "night",
  "swing": "V",
  "preset": "home"
}
```

Should it be like this, as it is in `state/status`? 

```json
{
  "online": true,
  "target": 20,
  "temp": 24,
  "outside": 27.5,
  "liquid": 15.5,
  "comp": 0,
  "demand": 100,
  "Wh": 853000,
  "fanfreq": 0,
  `"mode": "C",`   
  `"power": false`
  "fan": "night",
  "swing": "V",
  "preset": "home"
}
```

**Comment by revk** [comment]
I don't think HA understands *on*/*off* as separate from the `mode`, hence `mode` is `off` when *off*.

If you think HA can be configured to understand *on*/*off* as a separate setting, let me know the config, and I'll change it.

**Comment by Nick-Sills** [comment]
This might be relevant:

https://www.home-assistant.io/integrations/climate.mqtt/#power_command_topic

**Comment by revk** [comment]
Oooh, is that new, OK, that may be something I can change to - I don't have HA here to test though, so I'll have to make some test code for that.

**Comment by revk** [comment]
Ok looks like reported back as mode, so presumably still off as mode.

Ok, so I'll just add the power command stuff, and make a beta, try that in a few minutes.

**Comment by Nick-Sills** [comment]
OK, I can see that HA is now sending a 'power' command 👍 ,  but the AC isn't turning off:

<img width="173" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/162114112/edc3fcd4-be0d-4cc6-a005-9976fad2831d">

**Comment by revk** [comment]
Oooh, OK, so close, leave with me a moment.

**Comment by revk** [comment]
Ok try new beta in a minute.

**Comment by Nick-Sills** [comment]
Bingo! That's done it, and the Fan Mode persists as well. 😄 Thanks, and well done. 

While we're 'in the zone' can I request a couple more, hopefully minor, MQTT things for perfection?

This has been mentioned by me, and others, so it isn't something that an edge case.   Popular FTXM* units, and quite possibly others, don't have a 'Home' preset mode, so in the UI the control bounces around 'None' and 'Home', but settles on 'Home'. It also adds unnecessary text up the Climate display. Would it be possible to have a `nohome` switch to remove it from the list of presets, just leaving 'None', 'Eco' and 'Boost' if set. 

The final thing is a minor visual issue with icons, I think to do with the names of a state. I don't know exactly what it is at the moment but can dig in to find the cause. 

Thanks

**Comment by revk** [comment]
OK I'll add `no home`, beta in a minute. Not sure on icons.

**Comment by Nick-Sills** [comment]
Thanks. Home is now gone 👍 but selecting 'None' sets 'Eco' mode. Is the mapping incorrect, or is it an HA problem with stale mapping?

**Comment by revk** [comment]
I'll have to look when I am back.

**Comment by revk** [comment]
I literally look at first letter
```
           jo_bool (s, "econo", *value == 'e');
           jo_bool (s, "powerful", *value == 'b');
```

So None or none should unset both eco and powerful.

What MQTT is sent exactly?

**Comment by revk** [comment]
I'll make a new beta that actually has "none" as a preset value, try that.

**Comment by Nick-Sills** [comment]
That seems to have fixed it. 👍 Thanks

Finally, I think we might have covered the icon issue before, but I've got better clarity on it now:

HTTP Faikin sets the following hvac_actions for 'Heat' and 'Cool', other operational modes don't set an action, including 'Auto'. It doesn't matter that 'Idle' is never shown, and there's no attempt to set the havac_action for Auto. 

hvac_action: heating
hvac_action: cooling


This shows more distinct icons when either in Heat or Cooling, and setting the same for MQTT would make it consistent. 

HTTP Daikin and Faikin use 'heat_cool' / 'Heat/Cool' rather than 'auto' / "Auto' mode. These are different icon colours in HA. Having an option to set 'heat_cool' would make MQTT and HTTP both Daikin and Faikin consistent.

**Comment by revk** [comment]
Any clue where I would put that - we can't get the proper HVAC action, we use one of
```
const char *const hvac_action[] = { "off", "preheating", "heating", "cooling", "drying", "fan", "idle" };
```

**Comment by Nick-Sills** [comment]
https://www.home-assistant.io/integrations/climate.mqtt/

action_topic ?

heating for mode heat
cooling for mode cool
empty string otherwise I think

**Comment by revk** [comment]
OK we don't have actual mode (as S21 does not say!!!), so we only report when in Faikin auto mode, and that is the list I posted above.

**Comment by Nick-Sills** [comment]
I'm not sure I understand. I realize that we don't have the  actual HVAC action, the  HTTP comms spoofs it by forcing Heating for Heat mode and Cooling for Cool mode. Is it possible to do that with an MQTT action_topic ?

**Comment by revk** [comment]
The action topic is new, and is for reporting HVAC more, i.e. a live "is it heating or cooling", etc.

We don't get that from S21.

So we cannot really report it at all, but it was added recently for my "Faikin auto" mode, we were are controlling it to force heat or cool as needed to get to target temp, perhaps even based on external BLE temp sensor, etc. In that case we know what we are doing, so can report the HVAC mode.

But in other cases we cannot and report, I think, idle.

**Comment by Nick-Sills** [comment]
Understood. I was just suggesting that we fake it by always reporting Heating in Heat mode, and always reporting Cooling in Cool mode. I can see that this what Faikin HTTP is doing if I look at the state attributes for the Faikin HTTP climate entity. 

I'm not using "Faiin Auto" mode.

**Comment by revk** [comment]
Not out of the question...

**Comment by Nick-Sills** [comment]
If we could do that it'd be great, and also add a Heat/Cool switch.

HTTP Daikin and Faikin use 'heat_cool' / 'Heat/Cool' rather than 'auto' / "Auto' mode. These are different icon colours in HA. Having an option to set 'heat_cool' would make MQTT and HTTP both Daikin and Faikin consistent.

**Comment by revk** [comment]
I'll think about it - been a busy day!

**Comment by revk** [comment]
Ok try next beta...

**Comment by Nick-Sills** [comment]
Thanks, no change I'm afraid I'm not seeing Heating or Cooling state in HA. Is there a new switch for this, or is it always set?

Faikin-S3-MINI-N4-R2: 30e9f63 2024-06-09T18:07:02

**Comment by revk** [comment]
```
            daikin.action =
               (!daikin.power ? HVAC_OFF:
                daikin.mode == FAIKIN_MODE_HEAT ? HVAC_HEATING : //
                daikin.mode == FAIKIN_MODE_COOL ? HVAC_COOLING : //
                daikin.mode == FAIKIN_MODE_AUTO ? HVAC_HEAT_COOL : //
                daikin.mode == FAIKIN_MODE_DRY ? HVAC_DRYING : //
                daikin.mode == FAIKIN_MODE_FAN ? HVAC_FAN : //
                HVAC_IDLE );
```

So should be working?!

**Comment by Nick-Sills** [comment]
That looks good, but we only really need HVAC_HEATING  for FAIKIN_MODE_HEAT, HVAC_COOLING for FAIKIN_MODE_COOL to be consistent with Faikin HTTP . 

Give me a minute and I'll check the MQTT topics...

**Comment by Nick-Sills** [comment]
I can't seem to find the action_topic in th HA discovery payload

**Comment by revk** [comment]
Turn off `nohvacaction` setting.

**Comment by Nick-Sills** [comment]
Faikin-S3-MINI-N4-R2: 30e9f63 2024-06-09T18:07:02
Sorry, still not correct...

<img width="179" alt="image" src="https://github.com/revk/ESP32-Faikin/assets/162114112/e7b76892-98be-4ec5-8eca-af83b2b63a97">



</br>
HA Discovery payload:
**action_topic looks incorrect**

```json
{
  "unique_id": "34B7DA588E44",
  "dev": {
    "ids": [
      "34B7DA588E44"
    ],
    "name": "Villacana AC Back Bedroom",
    "mdl": "FTXM20R",
    "sw": "30e9f63",
    "mf": "RevK",
    "cu": "http://Villacana AC Back Bedroom.local/"
  },
  "icon": "mdi:thermostat",
  "~": "Faikin/Villacana AC Back Bedroom/command",
  "min_temp": 16,
  "max_temp": 32,
  "temp_unit": "C",
  "temp_step": 0.5,
  "temp_cmd_t": "~/temp",
  "temp_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "temp_stat_tpl": "{{value_json.target}}",
  "curr_temp_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "curr_temp_tpl": "{{value_json.temp}}",
  "mode_cmd_t": "~/mode",
  "mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "mode_stat_tpl": "{{value_json.mode}}",
  `"action_topic": "34B7DA588E44",`
  "action_template": "{{value_json.action}}",
  "payload_on": "1",
  "payload_off": "0",
  "power_command_topic": "~/power",
  "fan_mode_cmd_t": "~/fan",
  "fan_mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "fan_mode_stat_tpl": "{{value_json.fan}}",
  "fan_modes": [
    "auto",
    "low",
    "lowMedium",
    "medium",
    "mediumHigh",
    "high",
    "night"
  ],
  "swing_mode_cmd_t": "~/swing",
  "swing_mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "swing_mode_stat_tpl": "{{value_json.swing}}",
  "swing_modes": [
    "off",
    "H",
    "V",
    "H+V",
    "C"
  ],
  "pr_mode_cmd_t": "~/preset",
  "pr_mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "pr_mode_val_tpl": "{{value_json.preset}}",
  "pr_modes": [
    "none",
    "eco",
    "boost"
  ]
}
```
And nothing seems to have been  published:

![image](https://github.com/revk/ESP32-Faikin/assets/162114112/c77b96ad-64da-4539-9555-a7782a95c037)


Also, not sure why we've got `Villacana AC Back Bedroom/Faikin` and `Villacana AC Front Bedroom/Faikin`. It's not causing a routing problem for me though.

**Comment by revk** [comment]
Ah, I must have missed one when I made changes. I'll get on to that.

**Comment by revk** [comment]
I have issued a beta with corrected `action_topic`, please test.

I'm puzzled by the extra state messages, so will try and reproduce here.

**Comment by revk** [comment]
OK the extra messages are an edge case in the library, I have fixed. I'll make an issue, as the `action_topic` was broken in the recent issue.

**Comment by Nick-Sills** [comment]
Thanks for sticking with it.

We're nearly there. I can now see the "action" state being updated in the MQTT state payload. 👍  But, it looks like that documentation on MQTT Climate is either incomplete or wrong as it isn't being loaded into HA.  Looking at the Faikin HTTP entity states in HA, it appears that the state name should be `hvac_action` not `action`.

**Comment by Nick-Sills** [comment]
Hmm.. In MQTT explorer, I edited the state payload to change `action` to `hvac_action` and published it. It was only valid for a second or so as the Faikin publish state replaced it, but I couldn't see the HVAC Action change in the HA Climate entity. It may not be correct, but I guess we'll have to try it for real.

**Comment by revk** [comment]
I set
```
  "action_template": "{{value_json.action}}",
```
Which means it expects `action` as the field, surely.

**Comment by Nick-Sills** [comment]
I found a random example on the Internet, but I don't know if it's correct:

```json
	"action_topic":"MaxAir/livingroom/state",
	"action_template":"{{ value_json.hvac_action }}",
```

**Comment by Nick-Sills** [comment]
Saying that, every other example shows

```json
"action_template": "{{value_json.action}}",
```

**Comment by Nick-Sills** [comment]
Yes,  I don't think `hvac_action` is the correct status name. I'll keep digging ...

**Comment by Nick-Sills** [comment]
OK, a quick update. I haven't been able to spend much time on this, but I've discovered that the Faikin published topics paths and names are working correctly. 

I bypassed the MQTT HA discovery payload by creating my own Climate device using YAML.

This creates an MQTT Climate entity that **correctly** changes from Cool/Cooling to Heat/Heating etc..

<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/e5ff3c96-3961-455c-8783-4d9cc7688442" width="350">



```YAML
climate:
    - unique_id: "MQTT_TEST_4150"
      name: "Test Villacana AC Back Bedroom"
      modes:
        - "cool"
        - "heat"
        - "auto"
        - "off"
        - "fan_only"
        - "dry"
      mode_command_topic: "Faikin/Villacana AC Back Bedroom/command/mode"
      mode_state_topic: "Faikin/Villacana AC Back Bedroom/state/ha"
      mode_state_template: "{{ value_json.mode }}"
      fan_modes:
        - "auto"
        - "low"
        - "lowMedium"
        - "medium"
        - "mediumHigh"
        - "high"
        - "night"
      fan_mode_command_topic: "Faikin/Villacana AC Back Bedroom/command/fan"
      fan_mode_state_topic: "Faikin/Villacana AC Back Bedroom/state/ha"
      fan_mode_state_template: "{{ [value_json.fan](http://value_json.fan/) }}"
      swing_modes:
        - "off"
        - "H"
        - "V"
        - "H+V"
        - "C"
      swing_mode_command_topic: "Faikin/Villacana AC Back Bedroom/command/swing"
      swing_mode_state_topic: "Faikin/Villacana AC Back Bedroom/state/ha"
      swing_mode_state_template: "{{ value_json.swing }}"
      preset_modes:
        - "eco"
        - "boost"
      preset_mode_command_topic: "Faikin/Villacana AC Back Bedroom/command/preset"
      preset_mode_state_topic: "Faikin/Villacana AC Back Bedroom/state/ha"
      preset_mode_value_template: "{{ value_json.preset }}"
      temperature_unit: "C"
      temp_step: 0.5
      min_temp: 16
      max_temp: 32
      temperature_command_topic: "Faikin/Villacana AC Back Bedroom/command/temp"
      temperature_state_topic: "Faikin/Villacana AC Back Bedroom/state/ha"
      temperature_state_template: "{{ [value_json.target](http://value_json.target/) }}"
      current_temperature_topic: "Faikin/Villacana AC Back Bedroom/state/ha"
      current_temperature_template: "{{ value_json.temp }}"
      action_topic: "Faikin/Villacana AC Back Bedroom/state/ha"
      action_template: "{{value_json.action}}"
      retain: false
      device:
        identifiers: ["MQTT_TEST_4150"]
        name: "Test Villacana AC Back Bedroom"
        model: "FTXM20R"
        sw_version: "fa3a31e"
        manufacturer: "RevK"
        configuration_url: "http://Villacana AC Back Bedroom.local/"
```
<br/>
However, **the discovered device now has no MQTT HVAC entity**, everything else is there apart from the HVAC.

<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/cf5e4e84-9780-434c-b00b-1c475a0647cd" width="350">


homeassistant/climate/34B7DA588E44/config
```json
{
  "unique_id": "34B7DA588E44",
  "dev": {
    "ids": [
      "34B7DA588E44"
    ],
    "name": "Villacana AC Back Bedroom",
    "mdl": "FTXM20R",
    "sw": "8a8f3d8",
    "mf": "RevK",
    "cu": "http://Villacana AC Back Bedroom.local/"
  },
  "icon": "mdi:thermostat",
  "~": "Faikin/Villacana AC Back Bedroom/command",
  "min_temp": 16,
  "max_temp": 32,
  "temp_unit": "C",
  "temp_step": 0.5,
  "temp_cmd_t": "~/temp",
  "temp_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "temp_stat_tpl": "{{value_json.target}}",
  "curr_temp_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "curr_temp_tpl": "{{value_json.temp}}",
  "mode_cmd_t": "~/mode",
  "mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "mode_stat_tpl": "{{value_json.mode}}",
  "action_topic": "Faikin/Villacana AC Back Bedroom/state/ha",
  "action_template": "{{value_json.action}}",
  "payload_on": "1",
  "payload_off": "0",
  "power_command_topic": "~/power",
  "fan_mode_cmd_t": "~/fan",
  "fan_mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "fan_mode_stat_tpl": "{{value_json.fan}}",
  "fan_modes": [
    "auto",
    "low",
    "lowMedium",
    "medium",
    "mediumHigh",
    "high",
    "night"
  ],
  "swing_mode_cmd_t": "~/swing",
  "swing_mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "swing_mode_stat_tpl": "{{value_json.swing}}",
  "swing_modes": [
    "off",
    "H",
    "V",
    "H+V",
    "C"
  ],
  "pr_mode_cmd_t": "~/preset",
  "pr_mode_stat_t": "Faikin/Villacana AC Back Bedroom/state/ha",
  "pr_mode_val_tpl": "{{value_json.preset}}",
  "pr_modes": [
    "none",
    "eco",
    "boost"
  ]
}
```

I'm still investigating, but it points to a problem with the discovery payload.....

**Comment by Nick-Sills** [comment]
@revk Home assistant is complaining because, "none" isn't a valid preset mode:

```json
  "pr_modes": [
    `"none"`,
    "eco",
    "boost"
  ]
```
 It should be:
 
 ```json
   "pr_modes": [
    "eco",
    "boost"
  ]
 ```
 If "none" is removed then it stops the MQTT HVAC entity from being removed. 
 
 This won't fix the lack of HVAC action though.

**Comment by Nick-Sills** [comment]
OK I can confirm that if "none"  is removed, then the Climate entity shows Heat/Heating and Cool/Cooling. 

That was an absolute bugger to find.

**Comment by revk** [comment]
So all ok now?

**Comment by Nick-Sills** [comment]
Sorry not quite....

HVAC action doesn't change when switching to 'Auto'. So, for example, switching from 'Cool' to 'Auto'...

<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/e1cf70be-9724-4d84-863e-94e93de03ddf" width="350">

I'll investigate...

**Comment by Nick-Sills** [comment]
So:

```json 
 "mode": "auto",
  `"action": "heat_cool",`
```
`heat_cool` isn't a valid HVAC action. `heat_cool` is an alternative HVAC `mode` to `auto`.  It's the mode that's used in the Daikin and Faikin HTTP implementation, instead of `auto`.

`hvac_modes: fan_only, dry, cool, heat, heat_cool, off`.  Displayed text for `heat_cool' is "Heat/Cool"

TBH I don't know what happens if "action" is not sent for `heat_cool` but I'm hoping it looks like this:

From the faikin HTTP integration:
<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/c773c2f8-e57f-45d4-8c88-25e2328a2aa6" width="350">

**Comment by revk** [comment]
Just tell me what to send!

**Comment by Nick-Sills** [comment]
OK. 

I can't see in the MQTT ha discovery payload where we set the hvac modes, but can we change HVAC modes:

from:

`fan_only, dry, cool, heat, auto, off`.

 to:

`fan_only, dry, cool, heat, heat_cool, off`.  

`heat_cool` corresponds to `auto` as far as setting and retrieving the the HVAC mode on S21

I'm thinking that you may want to add a switch for this, with the same switch to send  the `action` status as well, in case some existing users have automations that set or test for `Auto` HVAC mode. 

mode `heat_cool` action  - **Do not send any action** 
mode `cool` action `"Cooling"`
mode `heat` action `"Heating"`
mode `dry` action `"Drying"` 
mode `fan_only` action `"Fan"`
mode `off` action `"Off"`

I'm hoping that this displays "Heat/Cool" as the HVAC action for mode `heat_cool`. 🤞

**Comment by revk** [comment]
We don't sent the list of modes, as there is a pre-defined list in HA.

If we are not sending `heat_cool`, surely it does not need to be in the list anyway.

And when you say "do not sent", what do we send? a blank string, or just a message with no `action` in it? That does not sound like it would update at all, and I see no reason it would updater to Heat/Cool. There must surely be a defined hvac_action for Heat/Cool?

**Comment by Nick-Sills** [comment]
**DON'T CHANGE ANYTHING UNTIL I'VE COMFIRMED THE BELOW BY PUBLISHING MY OWN MQTT TOPICS**
> We don't sent the list of modes, as there is a pre-defined list in HA.

OK, `heat_cool` is also predefined in HA. The current list of Faikin modes is the default, but you can send which modes are supported in the ha discovery payload.

`heat_cool` isn't mentioned here, but it **is** supported. 

https://www.home-assistant.io/integrations/climate.mqtt/#modes

So we need to send:

`"Default": "[heat_cool, off, cool, heat, dry, fan_only]"`

> If we are not sending heat_cool, surely it does not need to be in the list anyway.

So we want to change to send `"action": "heat_cool"` rather than `"action": "auto"` and also send the correct ha discovery payload as above. 

> And when you say "do not sent", what do we send? a blank string, or just a message with no action in it? That does not sound like it would update at all, and I see no reason it would updater to Heat/Cool. There must surely be a defined hvac_action for Heat/Cool?

`do not send` means **drop the json node**. An empty string is invalid. I think in this case HA will  use the string `Heat/Cool` as the current action in the Climate entity, which is exactly what the Daikin & Faikin HTTP integration is doing. 

I'm just trying to harmonize both the native Daikin integration with Faikin. MQTT integration, and in my opinion the Daikin integration is visually more appealing.

**Comment by Nick-Sills** [comment]
So, If I add `"Default": "[heat_cool, off, cool, heat, dry, fan_only]"` to the discovery payload then the Climate entity correctly adds Heat/Cool.</br>
<img src="https://github.com/revk/ESP32-Faikin/assets/162114112/cacc2b45-aff5-472a-89f4-156b04095329" width="250">

**But**, I can't test it further  because Faikin doesn't know what `heat_cool` is.  

So, if possible, could you make the changes outlined in my previous post, and enable Faikin to action `heat_cool` as if it were receiving and sending `auto` so we can see if it works.

Is that OK?

**Comment by Nick-Sills** [comment]
Sorry.

> So we want to change to send "action": "heat_cool" rather than "action": "auto" and also send the correct ha discovery payload as above.

Is incorrect. I meant **drop the node**

**Comment by Nick-Sills** [comment]
Sorry again, it's 

`"modes": ["heat_cool", "off", "cool", "heat", "dry", "fan_only"],`

In the discovery payload

**Comment by revk** [comment]
Latest code already sends `heat_cool` for auto, have you tried it?

**Comment by Nick-Sills** [comment]
[Home](http://192.168.100.165/) Faikin-S3-MINI-N4-R2: 4cc882f 2024-06-10T16:02:39

It seems that were sending `  "action": "heat_cool",` , **but we need to drop the node** and not send anything. 

Change

```json
  "Wh": 860300,
  "fanfreq": 8.7,
  "mode": "auto",
  "action": "heat_cool",
  "fan": "night",
  ```
  
  To
```json
  "Wh": 860300,
  "fanfreq": 8.7,
  "mode": "heat_cool",
  "fan": "night",
  ```

We also need to add:

`"modes": ["heat_cool", "off", "cool", "heat", "dry", "fan_only"], `

To the has discovery payload.

And, enable Faikin to treat `heat_cool` as it does with `auto`. Change the HVAC mode to Auto,

**Comment by revk** [comment]
OK so this is change `mode`, and not sending an `action` when auto.

Not sending `action` seems odd, but we can...

But why a change of `mode`, do you have documentation for the `heat_cool` being the "right" thing?

**Comment by revk** [comment]
I'll make a beta to not send `action` when in auto, see if that helps at all anyway.

**Comment by Nick-Sills** [comment]
> But why a change of mode, do you have documentation for the heat_cool being the "right" thing?

Sorry I'm not sure I understand. We need to change the Faikin supported modes in the ha discovery payload to:

`"modes": ["heat_cool", "off", "cool", "heat", "dry", "fan_only"], `


And the current *status*, when 'heat_cool` is selected to:

`"mode": "heat_cool",`

Is the current mode set by the HVAC unit.  **this corresponds to 'Auto' on S21**

**Comment by revk** [comment]
OK by *why* do we need to?

What makes `heat_cool` *right* and `auto` *wrong* in the list of modes exactly? Where is that documented?

**Comment by revk** [comment]
OK I'll make a beta with that... Try it!

**Comment by Nick-Sills** [comment]
Thanks, updated.. 

Discovery payload seems good, but, unfortunately, we're now sending action `idle` with mode `heat_cool`

```json
  "mode": "heat_cool",
  "action": "idle",
 ```

**Comment by Nick-Sills** [comment]
I need go offline for a couple of hours....

**Comment by revk** [comment]
Oh I thought I had suppressed idle! I'll look when back at my desk.

**Comment by revk** [comment]
OK try next beta

**Comment by Nick-Sills** [comment]
Faikin-S3-MINI-N4-R2: 43650e6 2024-06-11T11:06:26

Thanks

Faikin is behaving exactly as requested 👍 , but Home Assistant isn't playing ball with displaying the correct HVAC 'Action' during 'Heat/Cool' mode. 

**Don't do anything, Leave it with me to investigate this deeper**

**FYI:** ESPHOME has a much better description of the HVAC modes, and justifies using `heat_cool`:
https://esphome.io/components/climate/index.html

| Mode       | Description                                                                                   |
|------------|-----------------------------------------------------------------------------------------------|
| OFF        | The device is manually set to off, the device is inactive.                                    |
| AUTO       | **The device should adjust the temperature dynamically. For example based on a schedule, or learned behavior** |
| HEAT       | The device is set to heat to reach a target temperature.                                      |
| COOL       | The device is set to cool to reach a target temperature.                                      |
| HEAT_COOL  | **The device should heat/cool to maintain a target temperature**                                |
| FAN_ONLY   | The device only has the fan enabled, no heating or cooling is taking place.                   |
| DRY        | The device is set to dry/humidity mode.            

From this description `AUTO` is not the correct mode, but `HEAT_COOL` is.. 👍

**Comment by Nick-Sills** [comment]
@revk I'm afraid I've hit a brick wall. 

In Home Assistant, with MQTT, it isn't possible to set the HVAC action string to behave the same as we see in the Daikin HTTP integration. For MQTT It needs the HVAC action to be the real state of the HVAC, and as we don't have that, we're going to have to revert. 

1. Leave the `heat_cool` mode as it is. 👍 If you read the table above, this is the correct mode, and this also matches the Daikin HTTP integration. 

2. Remove the `"modes": ["heat_cool", "off", "cool", "heat", "dry", "fan_only"], ` from the HA discovery payload

3. Stop publishing the state topic  `"action":` payload

After this, the Climate entity in HA is still be much better than it was, and If we ever get the real HVAC running state we can add the `action` status back. 

Thanks for your help

**Comment by revk** [comment]
We have an option not to publish `action` already, as a setting.

Beta issued without the modes set.

**Comment by MacriumBeta** [comment]
Updated.

> Beta issued without the modes set.

This doesn't seem correct I'm afraid. Please re-read my previous post. Thanks

 > Leave the heat_cool mode as it is. 👍 If you read the table above, this is the correct mode, and this also matches the Daikin HTTP integration.

**Comment by revk** [comment]
OK confused, as I am sure I read you wanted the mode list removed - I must have misread, sorry. I'll put them back.

**Comment by Nick-Sills** [comment]
We're good. 👍 

Comparison of HTTP  and MQTT entities. The only difference is the HVAC action for Cool, and Heat, but the rest matches.

![image](https://github.com/revk/ESP32-Faikin/assets/162114112/01a1c871-9c67-49de-ad4d-b2665ab9471a)

**Comment by Nick-Sills** [comment]
**The final problem already reported in this issue.**

> yes, it is through HA using MQTT. It does NOT behave the same using the webinterface.
> 
> I'd like to dump the mqtt, but I have no idea how to do that. Do you mean "debug" on webinterface?
> 
> also, the temps get crazy, on Heating it sets default of 18 C, on Dry it defaults to... 50 :). this only happens if going through OFF state: eg:
> 
> Off > heat > 18C Off > dry > 50C Off > cool > 18C
> 
> if i switch modes once the AC is started, it does not behave this way

https://github.com/revk/ESP32-Faikin/issues/349#issuecomment-2146888269

This was raised by @Swalabrr, and it is still a problem. See below:

https://github.com/revk/ESP32-Faikin/assets/162114112/a5351197-8121-40b5-9c09-4977d50ab1f0


Dry mode is a  **dehumidifier** mode and **should not update the set temperature**

Can this be easily fixed? Many thanks for sticking with it.

**Comment by Nick-Sills** [comment]
That would make sense.

**Comment by revk** [comment]
Interesting, code allows temp in cool, head, and dry!
But was not setting when in AUTO...
So a bug there too.
I'll set for cool, heat, and auto.

**Comment by Nick-Sills** [comment]
Faikin-S3-MINI-N4-R2: 579c531 2024-06-12T12:54:16

@revk We're all good!  Thanks again

@Swalabrr The issues that you have raised (and a bit more) should be all resolved now.
